Vagrant.configure("2") do |config|
    config.vm.box = "debian/jessie64"
    config.vm.network :private_network, ip: '192.168.88.22'
    config.vm.hostname = 'vagrant.local'
    config.vm.provision 'ansible' do |ansible|
        ansible.inventory_path = 'inventory'
        ansible.playbook = 'test.yml'
        ansible.limit = 'vagrant.local'
    end
end
